/*
 * readingList
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

type Book struct {
	Id int64 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Published int32 `json:"published,omitempty"`

	Pages int32 `json:"pages,omitempty"`

	Rating float32 `json:"rating,omitempty"`

	Genres []string `json:"genres,omitempty"`
}
